<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net480</TargetFramework>
    <AssemblyName>ImmersiveChefs.PerformanceTests</AssemblyName>
    <RootNamespace>ImmersiveChefs.PerformanceTests</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <RimWorldPerformanceTest>true</RimWorldPerformanceTest>
    <RimWorldPerformanceTestOwnerPackageId>fumblesneeze.immersivechefs</RimWorldPerformanceTestOwnerPackageId>
    <HarmonyAssemblyPath Condition="'$(HarmonyAssemblyPath)' == ''">$(DefaultSteamModContentFolder)\2009463077\Current\Assemblies\0Harmony.dll</HarmonyAssemblyPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\mods\ImmersiveChefs\ImmersiveChefs.csproj" />
    <ProjectReference Include="..\..\shared\RimWorldDevGateway.EndToEndTesting\RimWorldDevGateway.EndToEndTesting.csproj" />
    <ProjectReference Include="..\..\shared\RimWorldDevGateway.PerformanceTesting\RimWorldDevGateway.PerformanceTesting.csproj" />
    <Reference Include="Assembly-CSharp">
      <HintPath>$(DefaultRimWorldPath)\RimWorldWin64_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(DefaultRimWorldPath)\RimWorldWin64_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(HarmonyAssemblyPath)</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
