<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>PerformanceAnalyzer</AssemblyName>
    <RootNamespace>Analyzer</RootNamespace>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(DefaultSteamModContentFolder)\2009463077\Current\Assemblies\0Harmony.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
