<Project Sdk="Zlepper.RimWorld.ModSdk.Testing/0.0.9">
  <PropertyGroup>
    <RimWorldPath>$(DefaultRimWorldPath)</RimWorldPath>
    <RimWorldManagedPath>$(RimWorldPath)\RimWorldWin64_Data\Managed</RimWorldManagedPath>
    <SteamModContentFolder>$(DefaultSteamModContentFolder)</SteamModContentFolder>
    <RootNamespace>ImmersiveChefs.Tests</RootNamespace>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\ImmersiveChefs.EndToEndTests\GalleryClearance.cs" Link="GalleryClearance.cs" />
    <ProjectReference Include="..\..\mods\ImmersiveChefs\ImmersiveChefs.csproj" />
    <Reference Include="System.Web.Extensions" />
    <PackageReference Update="NUnit3TestAdapter" Version="6.2.0" PrivateAssets="all" />
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>RimWorldPath</_Parameter1>
      <_Parameter2>$([System.IO.Path]::GetFullPath('$(RimWorldPath)'))</_Parameter2>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>SteamModContentFolder</_Parameter1>
      <_Parameter2>$([System.IO.Path]::GetFullPath('$(SteamModContentFolder)'))</_Parameter2>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
