<Project Sdk="Zlepper.RimWorld.ModSdk.Testing/0.0.9">
  <PropertyGroup>
    <RimWorldPath>$(DefaultRimWorldPath)</RimWorldPath>
    <RimWorldManagedPath>$(RimWorldPath)\RimWorldWin64_Data\Managed</RimWorldManagedPath>
    <SteamModContentFolder>$(DefaultSteamModContentFolder)</SteamModContentFolder>
    <HarmonyAssemblyPath Condition="'$(HarmonyAssemblyPath)' == ''">$(SteamModContentFolder)\2009463077\Current\Assemblies\0Harmony.dll</HarmonyAssemblyPath>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\mods\PersonalBugfixes\PersonalBugfixes.csproj" />
    <Reference Include="0Harmony"><HintPath>$(HarmonyAssemblyPath)</HintPath><Private>true</Private></Reference>
    <PackageReference Update="NUnit3TestAdapter" Version="6.2.0" PrivateAssets="all" />
  </ItemGroup>
</Project>
