<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net480</TargetFramework>
    <AssemblyName>RimWorldDevGateway.IntegrationTesting</AssemblyName>
    <RootNamespace>RimWorldDevGateway.IntegrationTesting</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
