<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net480</TargetFramework>
    <AssemblyName>ImmersiveChefs.InGame.IntegrationTests</AssemblyName>
    <RootNamespace>ImmersiveChefs.InGame.IntegrationTests</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <RimWorldInGameIntegrationTest>true</RimWorldInGameIntegrationTest>
    <RimWorldIntegrationTestOwnerPackageId>fumblesneeze.immersivechefs</RimWorldIntegrationTestOwnerPackageId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\mods\ImmersiveChefs\ImmersiveChefs.csproj" />
    <ProjectReference Include="..\..\shared\RimWorldDevGateway.IntegrationTesting\RimWorldDevGateway.IntegrationTesting.csproj" />
    <Reference Include="Assembly-CSharp">
      <HintPath>$(DefaultRimWorldPath)\RimWorldWin64_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="ImmersiveChefs.InGame.IntegrationTests.integrationtests.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
