<Project Sdk="Zlepper.RimWorld.ModSdk.Testing/0.0.9">
  <PropertyGroup>
    <RimWorldPath>$(DefaultRimWorldPath)</RimWorldPath>
    <RimWorldManagedPath>$(RimWorldPath)\RimWorldWin64_Data\Managed</RimWorldManagedPath>
    <SteamModContentFolder>$(DefaultSteamModContentFolder)</SteamModContentFolder>
    <RootNamespace>RimWorldDevGateway.Tests</RootNamespace>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\mods\RimWorldDevGateway\RimWorldDevGateway.csproj" />
    <ProjectReference Include="..\..\shared\RimWorldDevGateway.EndToEndTesting\RimWorldDevGateway.EndToEndTesting.csproj" />
    <ProjectReference Include="..\..\shared\RimWorldDevGateway.IntegrationTesting\RimWorldDevGateway.IntegrationTesting.csproj" />
    <ProjectReference Include="..\..\tools\RimWorldDevGateway.Client\RimWorldDevGateway.Client.csproj" />
    <PackageReference Update="NUnit3TestAdapter" Version="6.2.0" PrivateAssets="all" />
  </ItemGroup>
</Project>
